version: '2.0'

services:
  frontend:
    build: ./frontend
    networks:
      - my_network
    ports:
      - "5173:5173"
  
  backend:
    build: ./backend
    networks:
      - my_network
    ports:
      - "8800:8800"
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mariadb:10.5.8
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_ROOT_PASSWORD: '12345678'
      MARIADB_ROOT_PASSWORD: '12345678'
    networks:
      - my_network
    ports:
      - "3306:3306"
    volumes:
      - ./data/conf.d:/etc/mysql/conf.d
      - ./data/logs:/logs
      - /usr/local/var/mysql:/var/lib/mysql
      - mysql_data:/var/lib/mysql
      - ./backend/books_table.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

networks:
  my_network:

volumes:
  mysql_data: