USE test;
CREATE TABLE IF NOT EXISTS books (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    cover VARCHAR(255) NOT NULL,
    price DECIMAL(20,4) NOT NULL
);
